#!/bin/bash

#keygen
gcc shared.c keygen.c -o keygen

#otp_enc_d
gcc shared.c otp_enc_d.c -o otp_enc_d

#otp_enc
gcc shared.c otp_enc.c -o otp_enc

#otp_dec_d
gcc shared.c otp_dec_d.c -o otp_dec_d

#otp_dec
gcc shared.c otp_dec.c -o otp_dec
